In [1]:
import pandas as pd

# Dataset Collection 

__Case Data__ : 
- Source : [CDC](https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36/data)
- Updated : 5/21/2022
- Local : [United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv](./data/United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv)

In [7]:
caseDF = pd.read_csv('./data/United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv')

In [6]:
caseDF = caseDF[['new_case','new_death']]

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
0,03/18/2021,NE,206980,NaN,NaN,298,0.0,2130,NaN,NaN,1,0.0,03/20/2021 12:00:00 AM,Not agree,Not agree
1,05/12/2022,CT,777064,696528.0,80536.0,1963,173.0,10883,8906.0,1977.0,0,0.0,05/13/2022 01:28:57 PM,Agree,Agree
2,10/04/2020,MD,127290,NaN,NaN,471,0.0,4092,3933.0,159.0,3,0.0,10/06/2020 12:00:00 AM,NaN,Agree
3,03/11/2021,MD,390490,NaN,NaN,924,0.0,8549,8345.0,204.0,19,0.0,03/13/2021 12:00:00 AM,NaN,Agree
4,04/21/2022,ID,445350,348949.0,96401.0,0,0.0,4918,4007.0,911.0,0,0.0,04/22/2022 02:15:21 PM,Agree,Agree
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50935,07/19/2020,NJ,178541,NaN,NaN,-10,21.0,15706,13732.0,1974.0,34,27.0,07/19/2020 12:00:00 AM,Not agree,Agree
50936,02/10/2021,FSM,1,1.0,0.0,0,0.0,0,0.0,0.0,0,0.0,02/11/2021 02:50:55 PM,Agree,Agree
50937,06/23/2021,RI,144659,NaN,NaN,30,0.0,2725,NaN,NaN,0,0.0,06/23/2021 12:00:00 AM,Not agree,NaN
50938,07/06/2021,OR,209494,209494.0,0.0,117,0.0,2782,2782.0,0.0,1,0.0,07/07/2021 02:48:49 PM,Agree,Agree
50939,11/22/2021,AZ,1245127,1127692.0,117435.0,3249,403.0,21942,19414.0,2528.0,2,0.0,11/23/2021 02:18:53 PM,Agree,Agree